# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamdata.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10streamdata.proto\")\n\nNumpyArray\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"}\n\nStreamData\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12%\n\x05preds\x18\x02 \x03(\x0b\x32\x16.StreamData.PredsEntry\x1a\x39\n\nPredsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.NumpyArray:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streamdata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMDATA_PREDSENTRY']._loaded_options = None
  _globals['_STREAMDATA_PREDSENTRY']._serialized_options = b'8\001'
  _globals['_NUMPYARRAY']._serialized_start=20
  _globals['_NUMPYARRAY']._serialized_end=61
  _globals['_STREAMDATA']._serialized_start=63
  _globals['_STREAMDATA']._serialized_end=188
  _globals['_STREAMDATA_PREDSENTRY']._serialized_start=131
  _globals['_STREAMDATA_PREDSENTRY']._serialized_end=188
# @@protoc_insertion_point(module_scope)
